### ISSUE TITLE
Can't play music (error no devices)

### ISSUE THREAD

**Issue by xenon0054** [dupontgu/retro-ipod-spotify-client#66]
Hello I've finally got Spot to auto start and a bunch of other problems fixed but when I try to play a song it gives me this error

"playing spotify:album:6Bp2ojsBc8CtNaYipdxCLt spotify:track:3ZcLmonVVD1MTQtmQb8yf3
error! no devices"

I saw in the Github issue #4 someone had this error but they fixed it so I applied the fix to mine and it didn't do anything. Got a solution or an idea?

**Comment by doris1347** [comment]
Had any Luck Yet?

**Comment by xenon0054** [comment]
> Had any Luck Yet?

Nope

**Comment by doris1347** [comment]
When I try to play a playlist or track it indexes 3 seconds and drops out to no devices (no audio) would you have any ideas?

**Comment by xenon0054** [comment]
Having the same issue,currently just messing around with the code if I find a solution I'll post it here

**Comment by doris1347** [comment]
Hi, I tried setting my device ID in seven places in spotify_manager.py with no success, the pi does boot to the "Spot" GUI with no faults click wheel loads and responds smoothly ... I am now using a Pi Zero 2W (boots very fast).

Don't know what I will try next, I will continue to study Spotipy & spotify_manager I believe the solution is there or Librespot! 🤔

**Comment by xenon0054** [comment]
Hello @doris1347 I don't if you tried this but on step 12 when configuring raspotify it says comment and fill: 
OPTIONS="--username <USERNAME> --password <PASSWORD>"
where it says USERNAME and PASSWORD, did you try entering your username and password. I tried it and it didn't work am I suppose to leave "<>" those in or not I tried both and none worked.

**Comment by doris1347** [comment]
Hi Xero (my name is: Banks) yes I tried that and it didn’t work for me as well.

I am now using a Zero 2W and the latest 32bit Raspian OS and latest Raspotify … it’s no longer required to enter the credentials you mentioned and I still have the problem … I even tried entering the Spotify Connect “device id” in 4 different places in Spotify_Manager with negative results.

I am going to try entering the same directly in “Spotipy” and see what happens.

I have tried to reach several of the contributors and only received a response from Guy DuPont :

Guy DupontSep-14 10:00 AM
Hi Banks, unfortunately I have no good answers for you at this moment. I have not had a chance to look at that project in a few months, and unfortunately I haven't even been able to get my hands on a Pi Zero 2W. I'm hoping to do an update in the coming months but truthfully I don't know when I'm going to get a chance - I have a baby due in a few weeks.

Xero- My personal e-mail address is ***@***.*** if you like you can contact me directly.

I will keep you updated on any progress on my end 😊

**Comment by doris1347** [comment]
No Do Not Leave Them In you must delete them!!!   "<>" 


Yes, when I was using a Zero version 1w I tried step 12 and issue #4 with negative results - I'm now using a Zero 2w which has a different config file due to the upgraded (Raspotify/librespot) "/etc/default/raspotify" doesn't exist in versions after 0.31.3.
The Zero 2W boots up really fast however poor on power consumption!

https://community.spotify.com/t5/Spotify-for-Developers/active-a-playback-device-with-API/td-p/4963267

Perhaps the above? Obtaining "device id"

**Comment by doris1347** [comment]
https://community.spotify.com/t5/Spotify-for-Developers/active-a-playback-device-with-API/td-p/4963267

Obtaining "device id"

**Comment by doris1347** [comment]
Path to Spotipy:
 cd .local/lib/python3.9/site-packages/spotipy

nano client.py        (line 1725)

**Comment by doris1347** [comment]
I just wonder if this project "Spot" can really stream from Spotify as a "standalone" Spotify Connect  client or only act as a remote control and speaker for another Spotify Premium Device?

**Comment by doris1347** [comment]
I just tried entering my "Spots device id in (3) places in Spotipy with negative results, can select track however won't play what I've  selected!

**Comment by doris1347** [comment]
Xero read all the above

**Comment by xenon0054** [comment]
Sorry I've been a little busy today. Thank you so much for the new information and the links I think just from reading the articles I have an idea that could possibly solve this issue (.01% my idea works). I'll have ti try it when I get home.

**Comment by xenon0054** [comment]
Sorry I've been a little busy today. Thank you so much for the new information and the links I think just from reading the articles I have an idea that could possibly solve this issue (.01% my idea works). I'll have ti try it when I get home.

**Comment by doris1347** [comment]
https://community.spotify.com/t5/Closed-Ideas/Desktop-Connect-keyboard-shortcut-to-listen-on-another-device/idi-p/5179340

Here’s Another! 😊✅

**Comment by doris1347** [comment]
https://developer.spotify.com/documentation/web-api/guides/using-connect-web-api/#viewing-active-device-list

And Another

**Comment by doris1347** [comment]
https://spotipy.readthedocs.io/en/master/

**Comment by doris1347** [comment]
https://community.spotify.com/t5/Spotify-for-Developers/Invalid-redirect-URI-after-authorization/td-p/5425401

**Comment by doris1347** [comment]
https://community.spotify.com/t5/Spotify-for-Developers/Invalid-redirect-URI-after-authorization/td-p/5425401

**Comment by doris1347** [comment]
https://community.spotify.com/t5/Desktop-Mac/Spotify-Connect-Spotify-Switches-Playback-Device-Randomly/td-p/1106484/page/4

**Comment by doris1347** [comment]
Good Luck Xero … I’ve exhausted all of my ideas! 😞

**Comment by doris1347** [comment]
Perhaps it's a router/firewall issue? 🤔

**Comment by xenon0054** [comment]
I don't think it could be that, I think it could be that the dependencies were updated and this github isn't up to date on it.

**Comment by doris1347** [comment]
Interesting!

**Comment by doris1347** [comment]
Hmmm ... Interesting!
Now that gives me an iDea!
However I think it's the "Spot App." that's not up to date on it (incompatible with Bullseye & Raspotify versions above 0.31.8).

**Comment by doris1347** [comment]
Guy DuPont Says:

'Streaming from Spotify was surprisingly simple. I installed [Raspotify](https://github.com/dtcooper/raspotify), which just runs as a daemon and handles everything once you've authenticated. When it's running, the Pi appears as a "Spotify Connect" device on your account, and you can instruct it to takeover playback via an HTTP request (or using the UI of another authenticated Spotify client!)."

Makes you think it can only be a remote control for another authenticated connect device which I do have working as such.

**Comment by doris1347** [comment]
https://discourse.osmc.tv/t/raspotify-librespot-not-working-after-november-update/91598

Raspotify/librespot not working after November-2021 update/91598

**Comment by doris1347** [comment]
https://discourse.osmc.tv/t/howto-spotify-connect-support-via-raspotify-librespot/38348?page=4

**Comment by doris1347** [comment]
https://forums.raspberrypi.com/viewtopic.php?t=334874

**Comment by doris1347** [comment]
https://github.com/forslund/spotify-skill/issues/151

**Comment by doris1347** [comment]
https://community.spotify.com/t5/Other-Podcasts-Partners-etc/Raspotify-suddenly-give-no-sounds-music-but-shows-it-s-playing/td-p/5407494

**Comment by doris1347** [comment]
https://forums.raspberrypi.com/viewtopic.php?t=334874

**Comment by doris1347** [comment]
Xero, Let me know what you think?

**Comment by doris1347** [comment]
I think your right in regards to upgraded dependencies breaking not only 0.31.8.1 (was the last version to be built with ARMv6 support) but raspotify_0.31.3.librespot.v0.3.1-19 as well, all newer versions of Raspotify probably fails because Newer Raspbian OS and/or Guys "Spot" app.

Perhaps it's time to find a replacement for Raspotify with an alternative that's compatible with Guy's app and ARMv71.

I'm using the pi Zero 2W with current Raspbian OS and latest Raspotify I would assume even it's incompatible with the "Spot" app.

In a private message to me Guy mentioned a possible update to the project in a few months probably with the Zero 2W in mind.

**Comment by xenon0054** [comment]
My idea failed, I tried all possible ideas and just can't think of anything. I think im going to take a break from this project and I'll come back to this project some other time. Thank you so much for the information and your help, you've been amazing.

**Comment by doris1347** [comment]
Yeah I don't think there's much we can do ... Thanks for your participation.

**Comment by doris1347** [comment]
Did you see this:
https://github.com/syproduction/ipodrpi

**Comment by xenon0054** [comment]
Nope never seen this, im going to try it out right now

**Comment by doris1347** [comment]
https://hackaday.io/project/182282-ipodrpi

**Comment by doris1347** [comment]
Hey Xero, 

With my iPhone's Spotify Device id entered into the code of spotify_manager (line 176) I can completely control Spotify of the iPhone, however the iPhone has to be on with its Spotify app. Running

Did you ever try that?

**Comment by xenon0054** [comment]
No I've never tried that, but I did put the device id of the ipod itself in line 282 device id = "1234" in Spotify_manager and when I selected a song on the ipod it loaded the song name on the now playing screen and played for 3 seconds no audio unfortunately.

**Comment by doris1347** [comment]
Thanks

**Comment by doris1347** [comment]
https://github.com/dtcooper/raspotify/discussions/526

**Comment by doris1347** [comment]
Hey Xero ... Thje below is definitely getting me somewhere: 

1) Image & Install Rasbian OS Legacy Buster

2) Go through the "Spot" install however install Raspotify as per below (Do Not Install as per "Spot" Install)!

3) https://pimylifeup.com/raspberry-pi-spotify/       Do Not Install Raspotify until below!

4) sudo wget https://github.com/dtcooper/raspotify/releases/download/0.31.8.1/raspotify_0.31.8.1.librespot.v0.3.1-54-gf4be9bb_armhf.deb

5) sudo apt install ./raspotify_0.31.3.librespot.v0.3.1-19-gbbd575e_armhf.deb

6) Continue with remaining "Spot" dependency install, remember to clone Retro-iPod-Spotify-Client before applying requirements.txt to frontend folder!

FYI - https://github.com/dtcooper/raspotify/wiki/Migration-from-older-versions-to-0.31.4-and-beyond

Now working on getting Audio working.

**Comment by xenon0054** [comment]
Thanks for the information I will certainly try this out once I'm home. If you have any trouble with the bluetooth try this it helped me a lot: https://github.com/bablokb/pi-btaudio

And if your Bluetooth speaker isn't connecting at all try this command it helped me: 
sudo apt-get install pulseaudio pulseaudio-module-bluetooth

and to test it out just load an mp3 file in it and download a mp3 player to test it 
(for mp3 player I used mpg123 here is a way to install it)

sudo apt-get update
sudo apt-get install mpg123
mpg123 your-music.mp3

**Comment by doris1347** [comment]
Thanks!
Just remember I'm using an RPI Zero 2W
However all of the software I'm using  is 32bit 

See below:
https://linuxadictos.com/en/raspberry-pi-will-now-have-two-versions-available%3A-stable-and-legacy.html

**Comment by doris1347** [comment]
Thanks! ... for the command line mp3 player

Here's The Solution:

I'm now using the desktop version of Legacy Raspberry PiOs Buster v.10 & Raspotify 14.0 on my Zero 2W ... Issue Solved!!!
The Zero 2W boots up really fast however poor on power consuption!

Good idea your considering Retro - Dependency.

**Comment by doris1347** [comment]
If you get a “PIL” problem do the below:
sudo apt-get install python3-pil python3-pil.imagetk

**Comment by doris1347** [comment]
pi@Raspotify:~$ sudo systemctl status raspotify
* raspotify.service - Raspotify (Spotify Connect Client)
   Loaded: loaded (/lib/systemd/system/raspotify.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2022-09-20 14:26:06 BST; 2min 0s ago
     Docs: https://github.com/dtcooper/raspotify
           https://github.com/librespot-org/librespot
           https://github.com/dtcooper/raspotify/wiki
           https://github.com/librespot-org/librespot/wiki/Options
 Main PID: 948 (librespot)
    Tasks: 1 (limit: 871)
   CGroup: /system.slice/raspotify.service
           `-948 /usr/bin/librespot

Sep 20 14:27:54 Raspotify librespot[948]: [2022-09-20T13:27:54Z WARN  libmdns::fsm] error sending packet Os { code: 99, kind: AddrNotAvailable, message: "Cannot assign requested address" }
Sep 20 14:27:56 Raspotify librespot[948]: [2022-09-20T13:27:56Z WARN  libmdns::fsm] error sending packet Os { code: 99, kind: AddrNotAvailable, message: "Cannot assign requested address" }
Sep 20 14:27:56 Raspotify librespot[948]: [2022-09-20T13:27:56Z WARN  libmdns::fsm] error sending packet Os { code: 99, kind: AddrNotAvailable, message: "Cannot assign requested address" }
Sep 20 14:27:56 Raspotify librespot[948]: [2022-09-20T13:27:56Z WARN  libmdns::fsm] error sending packet Os { code: 99, kind: AddrNotAvailable, message: "Cannot assign requested address" }
Sep 20 14:27:58 Raspotify librespot[948]: [2022-09-20T13:27:58Z WARN  libmdns::fsm] error sending packet Os { code: 99, kind: AddrNotAvailable, message: "Cannot assign requested address" }
Sep 20 14:27:58 Raspotify librespot[948]: [2022-09-20T13:27:58Z WARN  libmdns::fsm] error sending packet Os { code: 99, kind: AddrNotAvailable, message: "Cannot assign requested address" }
Sep 20 14:27:58 Raspotify librespot[948]: [2022-09-20T13:27:58Z WARN  libmdns::fsm] error sending packet Os { code: 99, kind: AddrNotAvailable, message: "Cannot assign requested address" }
Sep 20 14:27:58 Raspotify librespot[948]: [2022-09-20T13:27:58Z WARN  libmdns::fsm] error sending packet Os { code: 99, kind: AddrNotAvailable, message: "Cannot assign requested address" }
Sep 20 14:27:58 Raspotify librespot[948]: [2022-09-20T13:27:58Z WARN  libmdns::fsm] error sending packet Os { code: 99, kind: AddrNotAvailable, message: "Cannot assign requested address" }
Sep 20 14:27:58 Raspotify librespot[948]: [2022-09-20T13:27:58Z WARN  libmdns::fsm] error sending packet Os { code: 99, kind: AddrNotAvailable, message: "Cannot assign requested address" }

**Comment by doris1347** [comment]
it plays longer however drops out, when I run, sudo systemctl status raspotify I get the above errors 

Still working on "No "Audio my blutooth speaker is paired and connected (easy I have a desktop environment).

**Comment by doris1347** [comment]
Entered my device id in all the usual placws in Spotipy and Spotify_Manager

**Comment by doris1347** [comment]
Thanks again for the terminal player!

**Comment by doris1347** [comment]
Perhaps we need to continue trying older versions of Raspbian & Raspotify until it works correctly .

**Comment by doris1347** [comment]
Clickwheel working again tracks Increment_UP completely as expected (more then 3 seconds ;-) 
Just need to get the correct Audio Driver installed for this older version of Raspbian and I will have a fully functioning "Spot" .... !

Thank You for putting me on to the Dependency path I could not have done this without You !!! Take a Bow! - _Xero._ Be Well!

**Comment by doris1347** [comment]
Just a note there's more to it then the above ... reach out to me if you need more info!

**Comment by xenon0054** [comment]
Congratulations on solving the issue!! I can't wait to try it once I'm home. Thank you so much for helping me and guiding me, couldn't have done this without you.

**Comment by doris1347** [comment]
The latest is that it does work!
You must have a Spotify Premium Account!!!
Use Raspberry OS imager to image Legacy Buster 10 & download and install Raspotify 14.0 everything works as Stand-Alone!! ---- Raspotify 15.0 or 16.0 probably will work as well, however for me 0.14.0 worked best ... nothing higher worked for me the config file at "/etc/default/raspotify" doesn't exist in versions after 0.31.3.

The config file at /etc/default/raspotify does exist in v. 14.0, 15.0 and 16.

If you get a “PIL” error do the below:
sudo apt-get install python3-pil python3-pil.imagetk

File "spotifypod.py", line 13, in
from PIL import ImageTK, Image
ImportError: cannot import name 'ImageTK' from 'PIL' (/usr/lib/python3/dist-packages/PIL/init.py

It might be necessary to delete __pycache__ from the frontend folder and reboot to make everything work ( rm -r __pycache__ ) it will be recreated automatically upon rebooting. 

Note: From Spotify "A Device ID is unique and persistent to some extent (and for some clients). However, this is not guaranteed and any cached device_id should periodically be cleared out and re-fetched as necessary."

Note: You will need "bluealsa" (Alsa with Bluetooth) to be operational for Bluetooth audio in this older version. (This part is tricky however do-able)! 
Note: bluealsa does not play mp3 files!

You must have bluealsa installed and configured correctly for Bluetooth Audio and the SpoT to work!
(see below links):
https://sigmdel.ca/michel/ha/rpi/bluetooth_n_buster_01_en.html
https://sigmdel.ca/michel/ha/rpi/bluetooth_in_rpios_02_en.html

pulseaudio needs to be disabled not removed!

Check with: sudo systemctl status pulseaudio

**Comment by doris1347** [comment]
Thanks Again, If you need any help let me know this absolutely Works!😊✅

**Comment by doris1347** [comment]
https://www.sigmdel.ca/michel/ha/rpi/bluetooth_n_buster_01_en.html

**Comment by doris1347** [comment]
https://github.com/skuethe/MMM-Spotify/issues/146

^ Good info!

**Comment by doris1347** [comment]
he above will explain why selecting the "Spot device" in Spotify Connect Devices - can be difficult at times!

**Comment by xenon0054** [comment]
Thank you, right now I got some free time and will try it out your way, again thank you so much couldn't have gotten this far without you!

**Comment by doris1347** [comment]
Your Welcome: - I think eventually the "Spot Program's" Python code will probably need  to be re-written using latest Python   so it can be compatible with the latest versions of Raspberry pi OS (Bullseye or above) and the latest versions of Raspotify.

**Comment by rsappia** [comment]
Hi guys, not sure if this was already discussed but this issue looks like the one I had at the very beginning and it was solved by going premium on Spotify. I had my set up running for the last 1.5 years with no issues... Let me know if you want .e to share any part of the code or set up i have running ;)

**Comment by doris1347** [comment]
Hi Ricardo!!! ... I have and always have had a Premium account ... I read your article very nice.
When you boot your "Spot" is it ready to play tracks or do you need to first need to with your cellphone/computer to Select the "Spot" ... and is that selecting at times difficult?

I am using the 2.0' Adafruit screen. and the Latest Pi Zero 2W running 32bit Raspbian10 Buster & 32bit Raspotify 0.14.0. the problems occurred with the original Zero W as well ... The Zero 2W boots up really fast poor on power consumption.

My "Spot" is working now and with Bluetooth audio using older Raspbian Legacy Buster 10 desktop version and older Raspotify 14.0 newer versions wouldn't work for me probably due to new Python code. however, 0.15.0 & 0.16.0 probably would work as well.

Thanking Guy & Yourself! - for all your hard work!

**Comment by doris1347** [comment]
Guy, Ricardo and others had to be using Raspberry PiOs Buster 10 and Raspotify 14, ... 15 or 16 since they originally did their builds over 1.5 years ago the same versions that I'm using now that works!

They were all busy building their "Spots" and (refining the install instructions) around Jan - March of 2021 when Raspotify 16.0 would have been current Buster 10 as well.
Things broke in November of the same year with the updates, so anyone building the "Spot" after October 2021 would have problems that so many of us had the only plays for 3 seconds, no devices and no bluetooth audio issue since we were all attempting to install on Bullseye 11 and Raspotify v.0.31.1 or higher.

**Comment by xenon0054** [comment]
Thanks for the info, Yeah I installed Rasbian buster lite with raspotify 14.0 I was to get it to run but I still have the problem that it won't play music individually and wont output audio.  In your previous post I noticed you said "Had to use my e-mail address instead of the 7 digit number for user id in /etc/default/rasspotify which does exist in v. 14.0." What did you mean by that?

edit: Do I have to use Pi os buster desktop?

**Comment by doris1347** [comment]
No you shouldn't need Desktop what to you mean by individually ?

Is it working for you?

**Comment by xenon0054** [comment]
Correct I am using a pi zero w, When i select a song using raspotify nothing plays. Yes the audio does work i tested it using a mp3 file.

**Comment by doris1347** [comment]
That means nothing the mp3 played for me as well however the "Spot" would not ... the "Spot" Audio only worked after installing blualsa (Pulse Audio) alone is not good enough read the install article it explains everything!

**Comment by doris1347** [comment]
Is the track incrementing up ? did you log in to your Spotify app. with your cellphone or PC and then Select the "Spot"
If you can't you have to wait 30 min before selecting again !!! see below:
https://github.com/skuethe/MMM-Spotify/issues/146

**Comment by doris1347** [comment]
https://www.sigmdel.ca/michel/ha/rpi/bluetooth_in_rpios_01_en.html
Use this blualsa install instead !!!

**Comment by doris1347** [comment]
Sorry Zero use the previous bluasla install

**Comment by doris1347** [comment]
Okay use this link for pairing and connecting:
https://www.sigmdel.ca/michel/ha/rpi/bluetooth_in_rpios_01_en.html

**Comment by doris1347** [comment]
Hopefully Ricardo will get back to me.

**Comment by rsappia** [comment]
> Hi Ricardo !!! ... I have and always have had a Premium account ... I read your article ... Guy and Yourself are Geniuses !
> 
>     1. May I ask which version of Rasberry Pi OS and Raspotify your using?
> 
>     2. Do you ever have trouble selecting your ({["Spot" as a (is_active)"]}=True) device? ;)
> 
>     3. When you boot your "Spot" is it ready to play tracks or do you need to first be logged in to your Spotify app. with your cellphone or PC and then Select the "Spot" ... is that selecting at times difficult?
> 
>     4. If you would be willing to share the "Low Battery signal code" and would be willing to explain how and where to define an internal pull-up/down resistor  in the code that would be great.
> 
> 
> I am using the 2.0' Adafruit screen. and the Latest Pi Zero 2W running 32bit OS & 32bit Raspotify. the problems occurred with the original Zero W as well.
> 
> My "Spot" is working now using older PiOS Legacy Buster 10 desktop version and older Raspotify 14.0 newer versions wouldn't work for me probably due to new Python code could you remember which your using & did you upgrade to Pi OS Bullseye 11 and 0.42.6 Raspotify circa November/2021?
> 
> Thanking Guy & You! - so much for all your hard work! and your offer for assistance.

Hi there, sorry for the delay.

1. May I ask which version of Rasberry Pi OS and Raspotify your using?
I am running Raspbian GNU/Linux 10 (buster) and raspotify/unknown,now 0.16.0~librespot.v0.1.3-37-g0adb851 armhf 

3. Do you ever have trouble selecting your ({["Spot" as a (is_active)"]}=True) device? ;)
Can you elaborate on that? It has been a while since I played around with the code and I am not sure about what part are you referring to

5. When you boot your "Spot" is it ready to play tracks or do you need to first be logged in to your Spotify app. with your cellphone or PC and then Select the "Spot" ... is that selecting at times difficult?
I don't need to be loged on to my Spotify app, I just turn it on, and is ready to go :). On the other hand, I can see that my Spot is listed as a device if I open the cellphone app.

7. If you would be willing to share the "Low Battery signal code" and would be willing to explain how and where to define an internal pull-up/down resistor in the code that would be great.
I am not sure if I actually fully implemented this function, I need to double-check on the code and come back later to you ;)

**Comment by doris1347** [comment]
Thanks Ricardo ... do you have to select your "Spot" device before you can use? 

Do you have other connect devices on the same network?
Did you need to enter your device if anywhere in your cod? If you can share your Spotify_Manager.py code .

**Comment by doris1347** [comment]
Xero ... do you have trouble selecting your "Spot" device or like Ricardo it's ready t go at boot?

**Comment by xenon0054** [comment]
Right now I've been busy and haven't had time to apply the fixes. I might have time later today, But if you were able to get it working then I should be able to.

**Comment by doris1347** [comment]
sudo systemctl status bluealsa.service

Use to see status of bluealsa

**Comment by doris1347** [comment]
Hi Ricardo ... What I'm asking plainly is what did you do in the code that enables your 'Spot"device to operate once it finishes booting without needing to first select it in the Spotify connect devices list of your smartphone or PC?

**Comment by doris1347** [comment]
Hopefully Ricardo will get back to me soon.

**Comment by doris1347** [comment]
https://community.spotify.com/t5/iOS-iPhone-iPad/Downloading-A-Single-Song/td-p/1004368

**Comment by doris1347** [comment]
file:///var/mobile/Library/SMS/Attachments/74/04/502F295F-179C-47E9-AC45-C8D4F1ACED53/How%20to%20Know%20Which%20Raspberry%20Pi%20OS%20is%20Running%20(Easiest%20way)%20%E2%80%93%20RaspberryTips.png

**Comment by doris1347** [comment]
Hopefully Ricardo you can get back to me in regards to the above soon.

**Comment by doris1347** [comment]
Raspotify V.014.0 seems more stable then V.016.0 on the "Spot' .

**Comment by doris1347** [comment]
Xero ... bluealsa does not play mp3's!

**Comment by doris1347** [comment]
Hello,
Does anyone know how to make their 'Spot"device operate (select,_play_tracks _etc.) ... once it finishes booting without needing to first select it from the Spotify Connect Devices List of your smartphone or PC?

**Comment by doris1347** [comment]
Thank You, I figured it out, ;)

**Comment by doris1347** [comment]
Hi Michael, were you successful?😊

**Comment by doris1347** [comment]
Ricardo, I thought I had solved the issue of the "Spot" booting and being ready for use without the need to select the device from my phone or computer, well I did not ... did you need to do anything in your code to allow for that or do you think I may have a router/firewall issue?
Thanks.

**Comment by xenon0054** [comment]
I'm still having issues with playing audio. No audio comes from the pi with Bluetooth speaker, and when I click on a song on the pi it will give me an error no devices

**Comment by doris1347** [comment]
To attempt a fix for: "when I click on a song on the pi it will give me an error no devices":
1) You must have a Spotify Premium Account!!!
2) ssh into your Pi or connect a monitor & keyboard/mouse.
3) Type the command 
"sudo systemctl status raspotify" (without the quotes) then press enter.
Post a screenshot of your results.

To attempt a fix for: "No audio comes from the pi with Bluetooth speaker":
1) You must have bluealsa installed and configured correctly for Bluetooth Audio to work. 
(see below links):
https://sigmdel.ca/michel/ha/rpi/bluetooth_n_buster_01_en.html

 https://sigmdel.ca/michel/ha/rpi/bluetooth_in_rpios_02_en.html
2) ssh into your Pi or connect a monitor & keyboard/mouse.
3) Type the command 
"sudo systemctl status bluealsa" (without the quotes) then press enter.
Post a screenshot of your results.

Note: PulseAudio should not be removed!!!

Note: You will need "bluealsa" (Alsa with Bluetooth) to be operational for Bluetooth audio in this older version. (This part is tricky however do-able).

Note: bluealsa does not play .mp3 files!

Test bluealsa with a .wav file!
Once installed & configured - Change to the directory that includes your .wav files 
example: "aplay -D bluealsa MAIN.WAV"    (Capitals). (without the quotes) then press enter.

Should you decide to post or "pm" me your two screenshot results then based on those results I should be able to suggest corrective actions.

Below my bluealsa screenshot:

pi@Raspotify:~$ sudo systemctl status bluealsa
* bluealsa.service - BluezALSA proxy
   Loaded: loaded (/lib/systemd/system/bluealsa.service; static; vendor preset: enabled)
   Active: active (running) since Fri 2022-12-02 22:40:15 EST; 16h ago
 Main PID: 565 (bluealsa)
    Tasks: 3 (limit: 871)
   CGroup: /system.slice/bluealsa.service
           `-565 /usr/bin/bluealsa

Dec 02 22:40:15 Raspotify systemd[1]: Started BluezALSA proxy.

**Comment by doris1347** [comment]
https://sigmdel.ca/michel/ha/rpi/bluetooth_n_buster_01_en.html

**Comment by xenon0054** [comment]
pi@raspberrypi:~$ sudo systemctl status raspotify
● raspotify.service - Raspotify
   Loaded: loaded (/lib/systemd/system/raspotify.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Sun 2022-12-04 00:57:50 PST; 410ms ago
  Process: 1548 ExecStartPre=/bin/mkdir -m 0755 -p /var/cache/raspotify (code=exited, status=0/SUCCESS)
  Process: 1549 ExecStartPre=/bin/chown raspotify:raspotify /var/cache/raspotify (code=exited, status=0/SUCCESS)
  Process: 1550 ExecStart=/usr/bin/librespot --name ${DEVICE_NAME} $BACKEND_ARGS --bitrate ${BITRATE} $CACHE_ARGS $VOLUME_ARGS $OPTIONS (code=exited, status=101)
 Main PID: 1550 (code=exited, status=101)

Dec 04 00:57:50 raspberrypi librespot[1550]:                        at src/libstd/panicking.rs:270
Dec 04 00:57:50 raspberrypi librespot[1550]:   32:   0x9bd484 - std::panic::catch_unwind::ha972c7f8a413a94c
Dec 04 00:57:50 raspberrypi librespot[1550]:                        at src/libstd/panic.rs:394
Dec 04 00:57:50 raspberrypi librespot[1550]:   33:   0x9bd484 - std::rt::lang_start_internal::hdf6cc497202d2594
Dec 04 00:57:50 raspberrypi librespot[1550]:                        at src/libstd/rt.rs:51
Dec 04 00:57:50 raspberrypi librespot[1550]:   34:   0x4f4dc4 - main
Dec 04 00:57:50 raspberrypi librespot[1550]:   35: 0xb6cb7718 - __libc_start_main
Dec 04 00:57:50 raspberrypi systemd[1]: raspotify.service: Main process exited, code=exited, status=101/n/a
Dec 04 00:57:50 raspberrypi systemd[1]: raspotify.service: Failed with result 'exit-code'.

pi@raspberrypi:~$ sudo systemctl status bluealsa
● bluealsa.service - BluezALSA proxy
   Loaded: loaded (/lib/systemd/system/bluealsa.service; static; vendor preset: enabled)
   Active: active (running) since Sun 2022-12-04 08:40:15 GMT; 13min ago
 Main PID: 389 (bluealsa)
    Tasks: 3 (limit: 877)
   CGroup: /system.slice/bluealsa.service
           └─389 /usr/bin/bluealsa -p a2dp-source -p a2dp-sink

Dec 04 08:40:15 raspberrypi systemd[1]: Started BluezALSA proxy.

**Comment by doris1347** [comment]
Good Morning, ... I need to ask you a few questions:

1) Do you have a Spotify Premium Account?
2) Were you successful at generating your Authentication .cache  file?
3) Were you ever able to play a song even though you had no audio (example: - time lapse counter incremented all the way to the end of the song and not just freeze at 3 seconds)?

**Comment by doris1347** [comment]
The below happens to me as well until I can successfully use my cellphone's or computer's Spotify app. to select my "Spot" which is named "Raspotify" to authenticate, once selected successfully I get authenticated, and all works properly, I can then close the Spotify app!

pi@Raspotify:~$ sudo systemctl status raspotify
* raspotify.service - Raspotify
   Loaded: loaded (/lib/systemd/system/raspotify.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Sun 2022-12-04 08:19:05 EST; 2s ago
  Process: 1282 ExecStartPre=/bin/mkdir -m 0755 -p /var/cache/raspotify (code=exited, status=0/SUCCESS)
  Process: 1283 ExecStartPre=/bin/chown raspotify:raspotify /var/cache/raspotify (code=exited, status=0/SUCCESS)
  Process: 1284 ExecStart=/usr/bin/librespot --name ${DEVICE_NAME} $BACKEND_ARGS --bitrate ${BITRATE} $CACHE_ARGS $VOLUME_ARGS $OPTIONS (code=exited, status=101)
 Main PID: 1284 (code=exited, status=101)
pi@Raspotify:~$

The Below is what I get once I am successful at authenticating by using my Cellphone Spotify app. (This usually takes many attempts and it's best to wait awhile after a failed attempt.


pi@Raspotify:~$ sudo systemctl status raspotify
* raspotify.service - Raspotify
   Loaded: loaded (/lib/systemd/system/raspotify.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2022-12-04 22:48:11 EST; 3min 35s ago
  Process: 784 ExecStartPre=/bin/mkdir -m 0755 -p /var/cache/raspotify (code=exited, status=0/SUCCESS)
  Process: 785 ExecStartPre=/bin/chown raspotify:raspotify /var/cache/raspotify (code=exited, status=0/SUCCESS)
 Main PID: 786 (librespot)
    Tasks: 5 (limit: 871)
   CGroup: /system.slice/raspotify.service
           `-786 /usr/bin/librespot --name raspotify --backend alsa --bitrate 320 --disable-audio-cache --enable-volume-normalisation --linear-volume --initial-volume=100 --username <XXXXXXXXXXXXXX>

Dec 04 22:48:11 Raspotify systemd[1]: Started Raspotify.
Dec 04 22:48:11 Raspotify librespot[786]: [2022-12-05T03:48:11Z INFO  librespot] librespot (raspotify v0.14.0) 3672214 (2020-01-30). Built on 2020-02-16. Build ID: 7pZDdYUK
Dec 04 22:48:12 Raspotify librespot[786]: [2022-12-05T03:48:12Z INFO  librespot_core::session] Connecting to AP "ap-gue1.spotify.com:4070"
Dec 04 22:48:12 Raspotify librespot[786]: [2022-12-05T03:48:12Z ERROR librespot] Could not connect to server: bytes remaining on stream
Dec 04 22:51:20 Raspotify librespot[786]: [2022-12-05T03:51:20Z INFO  librespot_core::session] Connecting to AP "ap-gue1.spotify.com:4070"
Dec 04 22:51:20 Raspotify librespot[786]: [2022-12-05T03:51:20Z INFO  librespot_core::session] Authenticated as "XXXXXXXXX" !
Dec 04 22:51:20 Raspotify librespot[786]: [2022-12-05T03:51:20Z INFO  librespot_playback::audio_backend::alsa] Using alsa sink
Dec 04 22:51:20 Raspotify librespot[786]: [2022-12-05T03:51:20Z INFO  librespot_core::session] Country: "US"
Dec 04 22:51:21 Raspotify librespot[786]: [2022-12-05T03:51:21Z INFO  librespot_playback::player] Loading <Do You Really Want To Hurt Me> with Spotify URI <spotify:track:4cswb13Sn7wueZ6Vgqeyyw>
Dec 04 22:51:22 Raspotify librespot[786]: [2022-12-05T03:51:22Z INFO  librespot_playback::player] <Do You Really Want To Hurt Me> loaded

**Comment by doris1347** [comment]
a) There is a configuration file in bluealsa that needs to be properly configured ...  configure it to startup on boot as well.
b) Pulseaudio needs to be removed from being your default blutooth driver.
Note: The two links I posted, and the one below has everything you should need to accomplish the above

**Comment by doris1347** [comment]
How to remove pulseaudio:
https://forums.debian.net/viewtopic.php?t=110272

**Comment by doris1347** [comment]
I guess Ricardo's Country Code and Internet service behavior there spares him these Spotify Connect on non approved devices handshaking issues.

**Comment by xenon0054** [comment]
Good morning, yes I was able to play a .wav file through a speaker and yes I do have a premium account, I was also successful on generating the cache files, and no I never got it to play it wouldn't go in increments it would stay at 0. Thank you for the instructions I make sure to follow them in a little bit.

**Comment by doris1347** [comment]
Were you ever able to play a Spotify song track even though you had no audio (example: - time lapse counter incremented all the way to the end of the song and not just freeze at 3 seconds)?

**Comment by xenon0054** [comment]
No When I click a song the bar stays in the middle and the time lapse counter stays at zero

**Comment by doris1347** [comment]
That's because you were never authenticated by using your cellphone or computer's Spotify app.
You have to make that happen its trial and error be patient!

**Comment by xenon0054** [comment]
How do I authenticate it using my computer or phone?

**Comment by doris1347** [comment]
Can you see your "Spot" in the Spotify's app. Device list?

**Comment by xenon0054** [comment]
Yes I do see it on the list

**Comment by doris1347** [comment]
When I select my "Spot" that's on the device list if it fails to connect sometimes I have to wait a half hour before I try again to finally succeed!!!

That's how you authenticate.

**Comment by doris1347** [comment]
While waiting keep checking by using sudo systemctl status raspotify in terminal then when you see a change in the status of raspotify retry selecting from the Spotify apps. Device list !!!

If it fails keep trying starting from the beginning.

**Comment by doris1347** [comment]
Sometimes I do a systemctl start raspotify and wait before trying the above procedure.

There are several iterations :
systemctl status raspotify

systemctl start raspotify

systemctl restart raspotify

systemctl stop raspotify

I don't understand why we have to go through this, my guess is Spotify tries to discourage unofficial Spotify Connect devices.

As long as all else in your etc/default/raspotify config file is correct and the name in your developer app matches exactly the name in the config file, all you can do is keep trying

Try inputting your device ID in client.py of Spotipy and Spotify_manager.py files.

**Comment by xenon0054** [comment]
yeah I will try it in a minute im going to wait 3-5 minutes till i try to connect it

**Comment by doris1347** [comment]
You have:

systemctl status raspotify

systemctl start raspotify

systemctl restart raspotify

systemctl stop raspotify

**Comment by doris1347** [comment]
I don't understand why we have to go through this, my guess is Spotify tries to discourage unofficial Spotify Connect devices.

Ricardo says he does not need to do the above of so I wish he would share his method! 😉✅

**Comment by xenon0054** [comment]
Yes I was able to select the pi from the device list

**Comment by doris1347** [comment]
As long as all else in you etc/default/raspotify config file is correct and the name in your developer app matches the name in the config file, all you can do is keep trying 

Try inputting your device ID in client.py of Spotipy and Spotifymanager.py files.

**Comment by xenon0054** [comment]
what do you mean by the name of the developer app matches the name in the config file?
and by the way what raspotify version are you using? I'm using 14
Also where do I put my device id in the spotify_manager.py file?

**Comment by doris1347** [comment]
I am using Raspotify version 0.14.0 and Raspbian Legacy Buster 10.

Where you received your client ID and Client Secret, you then had to provide a name for your developer app. (See Below link):

https://developer.spotify.com/dashboard/applications/

**Comment by doris1347** [comment]
Where you received your client ID and Client Secret, you then had to provide a name for your developer app. (See Below link):

https://developer.spotify.com/dashboard/applications/

I am using Raspotify version 0.14.0 and Raspbian GNU/Linux 10 Legacy Buster .

Let me check the file line numbers I will get back to you shortly

**Comment by xenon0054** [comment]
Yeah I'd like to thank you for helping me out sorry if I caused any problems, I'm not super experienced in raspberry pis

**Comment by doris1347** [comment]
Spotify_Manager.py - Line 179   ...  I used the issue #41 suggested fix!
cd /home/pi/retro-ipod-spotify-client/frontend/
nano spotify_manager.py

def refresh_devices():
    device = UserDevice('xxxxxxxxxxxxxxxxxxxxxxxxxxxxx','raspotify', True)
    DATASTORE.setUserDevice(device)

client.py of Spotipy - Line 1726
cd .local/lib/python3.7/site-packages/spotipy/
nano client.py

        data = {"device_ids": ["xxxxxxxxxxxxxxxxxxxxxxxxxx"], "play": force_play}
        return self._put("me/player", payload=data)

Where "xxxxxxxxxxxxxxxx" is the device ID

For device ID:
You have to be logged-in to the Developer Dashboard Console then Click get token then copy all the terminal information in the lower black box then paste that into you computer's terminal and press enter



Cheers!

**Comment by xenon0054** [comment]
Im trying to get my device id but it isn't showing up
https://developer.spotify.com/console/get-users-available-devices/

Nevermind it showed up after reboot

**Comment by doris1347** [comment]
you have to be logged-in  then Click get token then copy all the terminal information in the lower black box then paste that into you computer's terminal and press enter

**Comment by doris1347** [comment]
I wish Ricardo would help us out.

**Comment by xenon0054** [comment]
For spotify_manager do I delete the old code for refresh_devices? and replace it with the one you gave me?

**Comment by doris1347** [comment]
Yes, delete & replace with what I gave you!
Also be sure your client ID, Client secret and redirect uri are exactly the same in your developer app. and config file !!!
I used: http://localhost:8888

**Comment by xenon0054** [comment]
It worked It can now play songs by itself
Now I have to get audio to work, my headphones connect and play .wav files but wont pass through the audio from raspotify

**Comment by doris1347** [comment]
Hallelujah !!! ✅✅✅ 😊

**Comment by xenon0054** [comment]
I followed the direction from the links you sent me but I still cant get bluetooth working 100% 
https://sigmdel.ca/michel/ha/rpi/bluetooth_n_buster_01_en.html

**Comment by doris1347** [comment]
What do you mean by 100% ?
Getting it to work is tricky even Guy Dupont mentioned that in his first YouTube video!
It's all about the configuration and getting bluealsa to startup upon boot.

Again, What do you mean by 100% ?

**Comment by xenon0054** [comment]
I can hear the .wav files. But using Spotifypod.py and click a song from spotify there is no audio

**Comment by doris1347** [comment]
It's all about the configuration and getting bluealsa to startup upon boot.

**Comment by xenon0054** [comment]
Oh ok, do you have any tips on that?

**Comment by doris1347** [comment]
If I can find the config file l will post it ... I may have just lucked out and it just worked it was hit and miss for me.

Give me awhile!

**Comment by xenon0054** [comment]
Thank you very much!

**Comment by doris1347** [comment]
Awhile back I hope I didn't offend you - none was intended!

**Comment by xenon0054** [comment]
Oh no worries, sometimes I work on this project then I get upset that it doesn't work then i leave the project abandoned. I'm sorry if I caused you any worries.

**Comment by doris1347** [comment]
No worries, I just attributed it to your being 17!

**Comment by doris1347** [comment]
Can you now boot right into "Spot" operation (like Ricardo) without going through the trial-and-error process ???

**Comment by xenon0054** [comment]
yes when I turn on the pi it boots right into the program, in order to use it I need my phone before choosing a song

**Comment by doris1347** [comment]
You're saying that you still have to select it from the Spotify Connect Device List? and does it select successfully immediately and can you do so repeatedly???

**Comment by xenon0054** [comment]
it works on the first try

**Comment by doris1347** [comment]
Did you try more than once ???

**Comment by xenon0054** [comment]
No once I put the code you gave me all i have to do is just click it once

**Comment by doris1347** [comment]
So it's working  (like Ricardo's) without going through the trial-and-error process repeatedly??Can you shutdown your Spot reboot and trey again and let me know the outcome!

**Comment by doris1347** [comment]
So it's working (like Ricardo's) without going through the trial-and-error process repeatedly??
Can you shut down your Spot reboot and try again and let me know the outcome!

**Comment by xenon0054** [comment]
When I reboot it, it does take a while to establish a connection, so i can't just load music off boot

**Comment by doris1347** [comment]
However it did reconnect when you used the Spotify Connect device list?
After approx. how many attempts?

**Comment by xenon0054** [comment]
I didn't count but around 5 minutes

**Comment by doris1347** [comment]
What returns with the below command?
alsamixer -D bluealsa

**Comment by doris1347** [comment]
Will get back to you in regards to bluealsa config

**Comment by doris1347** [comment]
What returns with the below command?
alsamixer -D bluealsa

**Comment by xenon0054** [comment]
It loads a program with the speaker volume in the middle

**Comment by doris1347** [comment]
You can select an audio card with F6.

Did you uninstall pulesaudio?

**Comment by doris1347** [comment]
Did you uninstall pulesaudio?

**Comment by xenon0054** [comment]
when I ran the code it just gives me error that the file doesn't exist so I think I uninstalled

**Comment by xenon0054** [comment]
when i press F6 i get the option defualt and hdmi 1 and enter device name, which one should i click?

**Comment by doris1347** [comment]
Use the Default:

**Comment by doris1347** [comment]
pi@Raspotify:~$ ls -a
.   .bash_aliases  .bash_profile  Bookshelf  .config  Desktop    .gnupg      Music       pigpio-master    .pp_backup  .rediscli_history          Templates    .vnc         .xsession-errors
..  .bash_history  .bashrc        .btout     .cups    Documents  .local      pi-btaudio  pi-power-button  .profile    retro-ipod-spotify-client  .thumbnails  .wget-hsts   .xsession-errors.old
-a  .bash_logout   bluez-alsa     .cache     .dbus    Downloads  master.zip  Pictures    .pki             Public      spotipy_oauth_demo         Videos       .Xauthority
pi@Raspotify:~$ cd bluez-alsa
pi@Raspotify:~/bluez-alsa$ ls -a
.   aclocal.m4  AUTHORS         build    config.guess  config.sub  configure.ac  doc   .github     INSTALL.md  LICENSE    m4        Makefile.am  misc     NEWS       src   test-driver
..  ar-lib      autom4te.cache  compile  config.h.in   configure   depcomp       .git  .gitignore  install-sh  ltmain.sh  MAIN.WAV  Makefile.in  missing  README.md  test  utils

**Comment by doris1347** [comment]
don't ask

**Comment by xenon0054** [comment]
its ok I will try to find the information on my own, Thank you very much for your help!

**Comment by doris1347** [comment]
Here you go:

https://github.com/dtcooper/raspotify/wiki/Play-via-Bluetooth-Speaker

https://github.com/Arkq/bluez-alsa

https://sigmdel.ca/michel/ha/rpi/bluetooth_n_buster_01_en.html

https://sigmdel.ca/michel/ha/rpi/bluetooth_in_rpios_02_en.html

There's a section on bluealsa configuration near the bottom of the below link:
https://github.com/bablokb/pi-btaudio



See  - below:

Bluealsa Configuration:

After installation,  nano /etc/asound.conf and insert the MAC address of your bluetooth-device in the line starting with defaults.bluealsa.device:

pcm.!default "bluealsa"
ctl.!default "bluealsa"
defaults.bluealsa.interface "hci0"
defaults.bluealsa.device "xxxxxxxxxxx"
defaults.bluealsa.profile "a2dp"

Note that you can run

bluetoothctl devices

which should give you the MAC-address of your bluetooth-speaker.

That's it for configuration, all scripts and daemons will use this MAC-address.

Now is the time to restart your system. After booting has finished and all daemons are up and running, your Pi should automatically connect to your speaker or headset. If not, run btaudio-connect.

Create the below file if it isn't there!

sudo nano /etc/asound.conf

and add:

pcm.!default "bluealsa"
ctl.!default "bluealsa"
defaults.bluealsa.interface "hci0"
defaults.bluealsa.device "XXXXXXXXXXX" Your MAC address!
defaults.bluealsa.profile "a2dp"

**Comment by doris1347** [comment]
There's a section on blualsa I think I did something there

**Comment by doris1347** [comment]
Configuration

After installation, edit the file /etc/asound.conf and insert the MAC address of your bluetooth-device in the line starting with defaults.bluealsa.device:

pcm.!default "bluealsa"
ctl.!default "bluealsa"
defaults.bluealsa.interface "hci0"
defaults.bluealsa.device "32:54:03:BB:CC:28"
defaults.bluealsa.profile "a2dp"

Note that you can run

bluetoothctl devices

which should give you the MAC-address of your bluetooth-speaker.

That's it for configuration, all scripts and daemons will use this MAC-address.

Now is the time to restart your system. After booting has finished and all daemons are up and running, your Pi should automatically connect to your speaker or headset. If not, run btaudio-connect.

**Comment by doris1347** [comment]
That's it !!! above!

**Comment by doris1347** [comment]
sudo nano /etc/asound.conf

pcm.!default "bluealsa"
ctl.!default "bluealsa"
defaults.bluealsa.interface "hci0"
defaults.bluealsa.device "40:EF:4C:13:32:2F"
defaults.bluealsa.profile "a2dp"

**Comment by doris1347** [comment]
That's my MAC Address be sure that yours is inputted !

**Comment by doris1347** [comment]
Your Welcome!

**Comment by xenon0054** [comment]
thank you, you've been super helpful

**Comment by doris1347** [comment]
Like I said I have to much time on my hands !!! smile!

**Comment by xenon0054** [comment]
I'm going to close this issue now

**Comment by doris1347** [comment]
Create the below file if it isn't there!
sudo nano /etc/asound.conf

**Comment by xenon0054** [comment]
yeah I got the audio to work now, couldn't have done it without you

**Comment by doris1347** [comment]
Our  "Spots" are "completely operational and all of there circuits are functioning perfectly"! 😉✅

**Comment by doris1347** [comment]
I would leave it open for others whom may need help

**Comment by doris1347** [comment]
Michael are you sure you obtained the device ID of you pi or cellphone ? 🤔

**Comment by xenon0054** [comment]
Yes when I went on the devices page it took a while for the pi to show up but I did get the pi device id

**Comment by doris1347** [comment]
What Bluetooth speaker are you using?

**Comment by doris1347** [comment]
Do a systemctl status Raspotify and see what returns.

**Comment by xenon0054** [comment]
Currently I'm away from my pi but from what I remember is I can safely disconnect my phone from the pi. The speaker I am using are the airpods first gen

**Comment by doris1347** [comment]
I'm asking while listening to Spotify music can you totally shutdown the Spotify app. Or totally power off your cellphone and still hear Spotify music playing if yes all is well if no you are not hearing Spotify from your pi your hearing the Spotify music from your cellphone.

**Comment by xenon0054** [comment]
Yes I can

**Comment by doris1347** [comment]
Okay, be stay safe! 😯✅

**Comment by doris1347** [comment]
If you'd like you can close this issue now.
